- hosts: iosxr
  gather_facts: no
  tasks:
    - name: Get running config
      cisco.iosxr.iosxr_command:
        commands: show running-config
      register: show_running_config
    - name: Copy config
      local_action: copy content="{{ show_running_config.stdout_lines }}" dest=/home/cisco/LTRPML-2208/current_configs/iosxr/{{ inventory_hostname }}.txt
    - name: Print Output
      debug: var=show_running_config 