- hosts: iosxr
  gather_facts: no
  tasks:
    - name: Get running config
      cisco.iosxr.iosxr_command:
        commands: show running-config
      register: show_running_config
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp/LTRMPL-2208/current_configs/iosxr/
        state: directory
    - name: Copy config
      local_action: 
        copy content="{{ show_running_config.stdout[0] | replace('\\n', '\n') }}" 
        dest=/tmp/LTRMPL-2208/current_configs/iosxr/{{ inventory_hostname }}.txt
    - name: Replace Strings
      lineinfile:
        path: /tmp/LTRMPL-2208/current_configs/iosxr/{{ inventory_hostname }}.txt
        regexp: '^(!!.*)'
        state: absent
    - name: Register current file
      stat:
        path: "/tmp/LTRMPL-2208/current_configs/iosxr/{{ inventory_hostname }}.txt"
        checksum: sha1
        get_checksum: yes
      register: current_checksum
#    - debug: var=current_checksum.stat.checksum
    - name: Register initial
      stat:
        path: "/home/cisco/LTRMPL-2208/initial_configs/iosxr/{{ inventory_hostname }}.txt"
        checksum: sha1
        get_checksum: yes
      register: inital_checksum
#    - debug: var=inital_checksum.stat.checksum
    - name: Check if the files are the same
      debug: msg="The /tmp/LTRMPL-2208/current_configs/iosxr/{{ inventory_hostname }}.txt and /home/cisco/LTRMPL-2208/initial_configs/iosxr/{{ inventory_hostname }}.txt are identical"
      failed_when: current_checksum.stat.checksum != inital_checksum.stat.checksum
      ignore_errors: true