- hosts: iosxr
  gather_facts: no
  tasks:
    - name: Restore initial configs
      cisco.iosxr.iosxr_config:
        src: "/home/cisco/LTRMPL-2208/initial_configs/iosxr/{{ inventory_hostname }}.txt"
        replace: config
        
#    - name: Apply target configs
#      cisco.iosxr.iosxr_config:
#        src: "/home/cisco/LTRMPL-2208/target_configs/iosxr/{{ inventory_hostname }}.txt"
#        replace: config

    - name: Get running config
      cisco.iosxr.iosxr_command:
        commands: 
        - show run | in hostname
#        - show ip route vrf all 
#        - show mpls forwarding
      register: show_output
    - debug: var=show_output