- hosts: iosxr
  gather_facts: no
  tasks:
    - debug: var=inventory_hostname
      tags:
        - initial
    - debug: msg="/home/cisco/LTRMPL-2208/initial_configs/iosxr/{{ inventory_hostname }}.txt"
      tags:
        - initial

    - name: Restore initial configs
      cisco.iosxr.iosxr_config:
        src: "/home/cisco/LTRMPL-2208/initial_configs/iosxr/{{ inventory_hostname }}.txt"
      tags:
        - initial

    - name: Restore initial configs
      cisco.iosxr.iosxr_config:
        src: "/home/cisco/LTRMPL-2208/initial_configs/iosxr/{{ inventory_hostname }}.txt"
        replace: config
        force: yes
        match: none
      tags:
        - initial

    - debug: var=inventory_hostname
      tags:
        - target
    - debug: msg="/home/cisco/LTRMPL-2208/initial_configs/iosxr/{{ inventory_hostname }}.txt"
      tags:
        - target

    - name: Apply target configs
      cisco.iosxr.iosxr_config:
        src: "/home/cisco/LTRMPL-2208/target_configs/iosxr/{{ inventory_hostname }}.cfg"
      tags:
        - target

    - name: Apply target configs
      cisco.iosxr.iosxr_config:
        src: "/home/cisco/LTRMPL-2208/target_configs/iosxr/{{ inventory_hostname }}.cfg"
        replace: config
        force: yes
        match: none
      tags:
        - target

    - name: Get running config
      cisco.iosxr.iosxr_command:
        commands: 
        - show run | in hostname
#        - show ip route vrf all 
#        - show mpls forwarding
      register: show_output
    - debug: var=show_output