- hosts: iosxr
  gather_facts: no
  tasks:
    - name: Execute show version 
      cisco.iosxr.iosxr_command:
        commands: show version
      register: show_version
    - name: Print Output
      debug: var=show_version 
