- hosts: iosxr
  gather_facts: no
  tasks:
    - name: Execute show version 
      cisco.iosxr.iosxr_command:
        commands: 
        - show version
        wait_for:
        - result[0] contains TEST